```javascript
window.labTests = {
  "Hematology": [
    { id: "H1", name: "CBC" },
    { id: "H2", name: "Hemoglobin" },
    { id: "H3", name: "RBC Count" },
    { id: "H4", name: "WBC Count" },
    { id: "H5", name: "Platelet Count" },
    { id: "H6", name: "ESR" },
    { id: "H7", name: "PCV" },
    { id: "H8", name: "MCV" },
    { id: "H9", name: "MCH" },
    { id: "H10", name: "MCHC" },
    { id: "H11", name: "Peripheral Smear" },
    { id: "H12", name: "Reticulocyte Count" },
    { id: "H13", name: "Bleeding Time" },
    { id: "H14", name: "Clotting Time" },
    { id: "H15", name: "Prothrombin Time" },
    { id: "H16", name: "APTT" },
    { id: "H17", name: "D-Dimer" },
    { id: "H18", name: "Fibrinogen" },
    { id: "H19", name: "Leukocyte Alkaline Phosphatase" },
    { id: "H20", name: "Bone Marrow Aspiration" },
    { id: "H21", name: "Hemoglobin Electrophoresis" },
    { id: "H22", name: "Coombs Test (Direct)" },
    { id: "H23", name: "Coombs Test (Indirect)" },
    { id: "H24", name: "Iron Studies" },
    { id: "H25", name: "Serum Ferritin" },
    { id: "H26", name: "Vitamin B12" },
    { id: "H27", name: "Folate" },
    { id: "H28", name: "G6PD Screening" }
  ],
  "Serology": [
    { id: "S1", name: "Widal Test" },
    { id: "S2", name: "CRP" },
    { id: "S3", name: "Rheumatoid Factor (RA)" },
    { id: "S4", name: "ASO Titer" },
    { id: "S5", name: "Anti-HCV" },
    { id: "S6", name: "HBsAg" },
    { id: "S7", name: "HIV I/II" },
    { id: "S8", name: "VDRL" },
    { id: "S9", name: "TPHA" },
    { id: "S10", name: "Toxoplasma IgG" },
    { id: "S11", name: "Toxoplasma IgM" },
    { id: "S12", name: "Rubella IgG" },
    { id: "S13", name: "Rubella IgM" },
    { id: "S14", name: "CMV IgG" },
    { id: "S15", name: "CMV IgM" },
    { id: "S16", name: "Typhidot" },
    { id: "S17", name: "Anti Streptolysin O" },
    { id: "S18", name: "Anti CCP" },
    { id: "S19", name: "Brucella Test" },
    { id: "S20", name: "Dengue NS1" },
    { id: "S21", name: "Dengue IgM" },
    { id: "S22", name: "Dengue IgG" },
    { id: "S23", name: "Leptospira" },
    { id: "S24", name: "ANA" },
    { id: "S25", name: "Anti-dsDNA" },
    { id: "S26", name: "H. Pylori IgG" },
    { id: "S27", name: "H. Pylori IgM" },
    { id: "S28", name: "HCV RNA" },
    { id: "S29", name: "HBV DNA" },
    { id: "S30", name: "TORCH Panel" }
  ],
  "Microbiology": [
    { id: "M1", name: "AFB Culture" },
    { id: "M2", name: "Fungal Culture" },
    { id: "M3", name: "Nasal Swab Culture" },
    { id: "M4", name: "Pleural Fluid Culture" },
    { id: "M5", name: "Ascitic Fluid Culture" },
    { id: "M6", name: "Genital Swab Culture" },
    { id: "M7", name: "Mycobacterium Culture" },
    { id: "M8", name: "Blood for Fungal Culture" },
    { id: "M9", name: "H. influenzae Culture" },
    { id: "M10", name: "E. coli Identification" },
    { id: "M11", name: "S. aureus Identification" },
    { id: "M12", name: "Pseudomonas Identification" },
    { id: "M13", name: "Klebsiella Identification" },
    { id: "M14", name: "Salmonella Identification" },
    { id: "M15", name: "Antibiotic Sensitivity" },
    { id: "M16", name: "ESBL Detection" },
    { id: "M17", name: "MRSA Screening" },
    { id: "M18", name: "Carbapenem Resistance" },
    { id: "M19", name: "Enterococcus Identification" },
    { id: "M20", name: "Candida Identification" },
    { id: "M21", name: "Yeast Culture" },
    { id: "M22", name: "Biofilm Formation Test" }
  ],
  "Histopathology": [
    { id: "HP1", name: "Biopsy" },
    { id: "HP2", name: "Skin Biopsy" },
    { id: "HP3", name: "Liver Biopsy" },
    { id: "HP4", name: "Renal Biopsy" },
    { id: "HP5", name: "Lymph Node Biopsy" },
    { id: "HP6", name: "Endometrial Biopsy" },
    { id: "HP7", name: "Breast Lump Biopsy" },
    { id: "HP8", name: "Bone Marrow Biopsy" },
    { id: "HP9", name: "Tumor Biopsy" },
    { id: "HP10", name: "Thyroid Biopsy" },
    { id: "HP11", name: "Prostate Biopsy" },
    { id: "HP12", name: "Muscle Biopsy" },
    { id: "HP13", name: "GI Tract Biopsy" },
    { id: "HP14", name: "Urinary Bladder Biopsy" },
    { id: "HP15", name: "Bone Biopsy" },
    { id: "HP16", name: "Appendix Histology" },
    { id: "HP17", name: "Colon Biopsy" },
    { id: "HP18", name: "Cervix Biopsy" },
    { id: "HP19", name: "Ovary Biopsy" },
    { id: "HP20", name: "Pancreatic Tissue Biopsy" },
    { id: "HP21", name: "Nerve Biopsy" },
    { id: "HP22", name: "Soft Tissue Tumor" },
    { id: "HP23", name: "Spleen Biopsy" },
    { id: "HP24", name: "Pituitary Gland Biopsy" },
    { id: "HP25", name: "Adrenal Gland Biopsy" },
    { id: "HP26", name: "Stomach Biopsy" },
    { id: "HP27", name: "Eye Tissue Biopsy" },
    { id: "HP28", name: "Tongue Biopsy" },
    { id: "HP29", name: "Testicular Biopsy" },
    { id: "HP30", name: "Vaginal Wall Biopsy" }
  ],
  "Biochemistry": [
    { id: "B1", name: "Blood Glucose (Fasting)" },
    { id: "B2", name: "Blood Glucose (Random)" },
    { id: "B3", name: "HbA1c" },
    { id: "B4", name: "Serum Urea" },
    { id: "B5", name: "Serum Creatinine" },
    { id: "B6", name: "Uric Acid" },
    { id: "B7", name: "Lipid Profile" },
    { id: "B8", name: "Cholesterol" },
    { id: "B9", name: "Triglycerides" },
    { id: "B10", name: "HDL" },
    { id: "B11", name: "LDL" },
    { id: "B12", name: "VLDL" },
    { id: "B13", name: "Liver Function Test (LFT)" },
    { id: "B14", name: "ALT (SGPT)" },
    { id: "B15", name: "AST (SGOT)" },
    { id: "B16", name: "ALP" },
    { id: "B17", name: "Bilirubin" },
    { id: "B18", name: "Total Protein" },
    { id: "B19", name: "Albumin" },
    { id: "B20", name: "Globulin" },
    { id: "B21", name: "Electrolytes (Na, K, Cl)" },
    { id: "B22", name: "Calcium" },
    { id: "B23", name: "Phosphorus" },
    { id: "B24", name: "Magnesium" },
    { id: "B25", name: "Amylase" },
    { id: "B26", name: "Lipase" },
    { id: "B27", name: "Iron" },
    { id: "B28", name: "TIBC" },
    { id: "B29", name: "LDH" },
    { id: "B30", name: "CK-MB" }
  ],
  "Blood Banking": [
    { id: "BB1", name: "Blood Grouping" },
    { id: "BB2", name: "Rh Typing" },
    { id: "BB3", name: "Cross Match (Major)" },
    { id: "BB4", name: "Cross Match (Minor)" },
    { id: "BB5", name: "Antibody Screening" },
    { id: "BB6", name: "Antibody Identification" },
    { id: "BB7", name: "Packed RBC Compatibility" },
    { id: "BB8", name: "Platelet Compatibility" },
    { id: "BB9", name: "Plasma Compatibility" },
    { id: "BB10", name: "Cryoprecipitate Compatibility" },
    { id: "BB11", name: "Blood Component Separation" },
    { id: "BB12", name: "Fresh Frozen Plasma (FFP)" },
    { id: "BB13", name: "Single Donor Platelets (SDP)" },
    { id: "BB14", name: "Random Donor Platelets (RDP)" },
    { id: "BB15", name: "Whole Blood Collection" },
    { id: "BB16", name: "Donor Screening" },
    { id: "BB17", name: "Infectious Marker Screening" },
    { id: "BB18", name: "Hemolysin Test" },
    { id: "BB19", name: "LISS Crossmatch" },
    { id: "BB20", name: "Saline Crossmatch" },
    { id: "BB21", name: "Enzyme Treated Cells" },
    { id: "BB22", name: "Cold Agglutinin" },
    { id: "BB23", name: "Blood Transfusion Reaction Workup" },
    { id: "BB24", name: "DAT" },
    { id: "BB25", name: "IAT" },
    { id: "BB26", name: "Du Test" },
    { id: "BB27", name: "Rosette Test" },
    { id: "BB28", name: "Kleihauer-Betke Test" }
  ],
  "Culture Tests": [
    { id: "C1", name: "Urine Culture" },
    { id: "C2", name: "Blood Culture" },
    { id: "C3", name: "Stool Culture" },
    { id: "C4", name: "Sputum Culture" },
    { id: "C5", name: "Wound Swab Culture" },
    { id: "C6", name: "CSF Culture" },
    { id: "C7", name: "Throat Swab Culture" },
    { id: "C8", name: "Genital Swab Culture" },
    { id: "C9", name: "Eye Swab Culture" },
    { id: "C10", name: "Ear Swab Culture" },
    { id: "C11", name: "Pus Culture" },
    { id: "C12", name: "Catheter Tip Culture" },
    { id: "C13", name: "Pleural Fluid Culture" },
    { id: "C14", name: "Ascitic Fluid Culture" },
    { id: "C15", name: "Bile Culture" },
    { id: "C16", name: "Synovial Fluid Culture" },
    { id: "C17", name: "Skin Swab Culture" },
    { id: "C18", name: "Vaginal Swab Culture" },
    { id: "C19", name: "Rectal Swab Culture" },
    { id: "C20", name: "Anaerobic Culture" },
    { id: "C21", name: "Aerobic Culture" },
    { id: "C22", name: "Environmental Culture" },
    { id: "C23", name: "Tissue Culture" },
    { id: "C24", name: "Surface Swab Culture" },
    { id: "C25", name: "Intraoperative Culture" },
    { id: "C26", name: "Dental Swab Culture" },
    { id: "C27", name: "Sterility Culture" }
  ],
  "Special Chemistry": [
    { id: "SC1", name: "T3" },
    { id: "SC2", name: "T4" },
    { id: "SC3", name: "TSH" },
    { id: "SC4", name: "Free T3" },
    { id: "SC5", name: "Free T4" },
    { id: "SC6", name: "Insulin" },
    { id: "SC7", name: "C-Peptide" },
    { id: "SC8", name: "Growth Hormone" },
    { id: "SC9", name: "Cortisol" },
    { id: "SC10", name: "ACTH" },
    { id: "SC11", name: "Prolactin" },
    { id: "SC12", name: "LH" },
    { id: "SC13", name: "FSH" },
    { id: "SC14", name: "Testosterone" },
    { id: "SC15", name: "Estrogen" },
    { id: "SC16", name: "Progesterone" },
    { id: "SC17", name: "PTH" },
    { id: "SC18", name: "Vitamin D" },
    { id: "SC19", name: "Beta HCG" },
    { id: "SC20", name: "CEA" },
    { id: "SC21", name: "AFP" },
    { id: "SC22", name: "CA-125" },
    { id: "SC23", name: "CA 19-9" },
    { id: "SC24", name: "CA 15-3" },
    { id: "SC25", name: "PSA" },
    { id: "SC26", name: "Free PSA" },
    { id: "SC27", name: "Ammonia" },
    { id: "SC28", name: "Homocysteine" },
    { id: "SC29", name: "Ceruloplasmin" },
    { id: "SC30", name: "Alpha-1 Antitrypsin" }
  ],
  "Molecular Biology": [
    { id: "MB1", name: "PCR for HCV" },
    { id: "MB2", name: "PCR for HBV" },
    { id: "MB3", name: "COVID-19 PCR" },
    { id: "MB4", name: "HIV RNA PCR" },
    { id: "MB5", name: "CMV DNA PCR" },
    { id: "MB6", name: "EBV DNA PCR" },
    { id: "MB7", name: "Mycobacterium TB PCR" },
    { id: "MB8", name: "HPV DNA Test" },
    { id: "MB9", name: "Chlamydia PCR" },
    { id: "MB10", name: "Gonorrhea PCR" },
    { id: "MB11", name: "BRCA1/BRCA2" },
    { id: "MB12", name: "Factor V Leiden" },
    { id: "MB13", name: "JAK2 Mutation" },
    { id: "MB14", name: "BCR-ABL" },
    { id: "MB15", name: "KRAS Mutation" },
    { id: "MB16", name: "EGFR Mutation" },
    { id: "MB17", name: "NRAS Mutation" },
    { id: "MB18", name: "Thalassemia Mutation" },
    { id: "MB19", name: "DMD Gene Test" },
    { id: "MB20", name: "CFTR Gene Test" },
    { id: "MB21", name: "HLA Typing" },
    { id: "MB22", name: "Gene Rearrangement" },
    { id: "MB23", name: "Multiplex PCR" },
    { id: "MB24", name: "Real-Time PCR" },
    { id: "MB25", name: "RT-PCR" },
    { id: "MB26", name: "cDNA Synthesis" },
    { id: "MB27", name: "Sanger Sequencing" },
    { id: "MB28", name: "Next Generation Sequencing (NGS)" },
    { id: "MB29", name: "MLPA" },
    { id: "MB30", name: "Gene Fusion Detection" }
  ]
};
```
