// Auto-generated test-data.js
window.testData = {
  "Hematology": [
    {"name": "Complete Blood Count (CBC) - Hemoglobin", "parameter": "g/dL", "normalRange": "12.0 - 17.5"},
    {"name": "CBC - White Blood Cells (WBC)", "parameter": "cells/uL", "normalRange": "4,000 - 11,000"},
    {"name": "CBC - Platelets", "parameter": "cells/uL", "normalRange": "150,000 - 450,000"},
    {"name": "Erythrocyte Sedimentation Rate (ESR)", "parameter": "mm/hr", "normalRange": "0 - 20"},
    {"name": "Peripheral Blood Smear", "parameter": "report", "normalRange": "Reference"},
    {"name": "Reticulocyte Count", "parameter": "%", "normalRange": "0.5 - 2.5"},
    {"name": "Mean Corpuscular Volume (MCV)", "parameter": "fL", "normalRange": "80 - 100"},
    {"name": "Mean Corpuscular Hemoglobin (MCH)", "parameter": "pg", "normalRange": "27 - 33"},
    {"name": "Mean Corpuscular Hemoglobin Concentration (MCHC)", "parameter": "g/dL", "normalRange": "32 - 36"},
    {"name": "Packed Cell Volume (PCV / Hematocrit)", "parameter": "%", "normalRange": "36 - 50"},
    {"name": "Bleeding Time", "parameter": "minutes", "normalRange": "2 - 7"},
    {"name": "Clotting Time", "parameter": "minutes", "normalRange": "6 - 10"},
    {"name": "Prothrombin Time (PT)", "parameter": "seconds", "normalRange": "11 - 15"},
    {"name": "INR", "parameter": "", "normalRange": "0.8 - 1.2"},
    {"name": "Activated Partial Thromboplastin Time (aPTT)", "parameter": "seconds", "normalRange": "25 - 40"},
    {"name": "D-dimer", "parameter": "ng/mL", "normalRange": "< 500"},
    {"name": "Fibrinogen", "parameter": "mg/dL", "normalRange": "200 - 400"},
    {"name": "Hemoglobin A1c (HbA1c)", "parameter": "%", "normalRange": "4.0 - 5.6"},
    {"name": "Bone Marrow Examination", "parameter": "report", "normalRange": "Reference"},
    {"name": "Coombs Test (Direct)", "parameter": "report", "normalRange": "Negative"}
  ],
  "Biochemistry": [
    {"name": "Blood Glucose (Fasting)", "parameter": "mg/dL", "normalRange": "70 - 100"},
    {"name": "Blood Glucose (Random)", "parameter": "mg/dL", "normalRange": "< 140"},
    {"name": "HbA1c", "parameter": "%", "normalRange": "4.0 - 5.6"},
    {"name": "Serum Urea", "parameter": "mg/dL", "normalRange": "7 - 20"},
    {"name": "Serum Creatinine", "parameter": "mg/dL", "normalRange": "0.6 - 1.3"},
    {"name": "Serum Sodium (Na+)", "parameter": "mmol/L", "normalRange": "135 - 145"},
    {"name": "Serum Potassium (K+)", "parameter": "mmol/L", "normalRange": "3.5 - 5.1"},
    {"name": "Serum Chloride (Cl-)", "parameter": "mmol/L", "normalRange": "98 - 107"},
    {"name": "Serum Bicarbonate (HCO3-)", "parameter": "mmol/L", "normalRange": "22 - 28"},
    {"name": "ALT/SGPT", "parameter": "IU/L", "normalRange": "7 - 56"},
    {"name": "AST/SGOT", "parameter": "IU/L", "normalRange": "10 - 40"},
    {"name": "Alkaline Phosphatase (ALP)", "parameter": "IU/L", "normalRange": "44 - 147"},
    {"name": "Total Bilirubin", "parameter": "mg/dL", "normalRange": "0.1 - 1.2"},
    {"name": "Direct Bilirubin", "parameter": "mg/dL", "normalRange": "0.0 - 0.3"},
    {"name": "Total Protein", "parameter": "g/dL", "normalRange": "6.0 - 8.3"},
    {"name": "Albumin", "parameter": "g/dL", "normalRange": "3.5 - 5.0"},
    {"name": "Serum Calcium", "parameter": "mg/dL", "normalRange": "8.6 - 10.2"},
    {"name": "Serum Phosphorus", "parameter": "mg/dL", "normalRange": "2.5 - 4.5"},
    {"name": "Lipid Profile - Total Cholesterol", "parameter": "mg/dL", "normalRange": "< 200"},
    {"name": "Lipid Profile - Triglycerides", "parameter": "mg/dL", "normalRange": "< 150"}
  ],
  "Serology": [
    {"name": "Hepatitis B Surface Antigen (HBsAg)", "parameter": "qualitative", "normalRange": "Negative"},
    {"name": "Hepatitis C Antibody (Anti-HCV)", "parameter": "qualitative", "normalRange": "Negative"},
    {"name": "HIV 1/2 Antibody", "parameter": "qualitative", "normalRange": "Negative"},
    {"name": "VDRL (Syphilis)", "parameter": "qualitative", "normalRange": "Non-reactive"},
    {"name": "Dengue NS1", "parameter": "qualitative", "normalRange": "Negative"},
    {"name": "Dengue IgM/IgG", "parameter": "qualitative", "normalRange": "Negative/Positive"},
    {"name": "Typhoid (Widal)", "parameter": "titer", "normalRange": "<1:80"},
    {"name": "C-Reactive Protein (CRP)", "parameter": "mg/L", "normalRange": "< 5"},
    {"name": "ASO (Antistreptolysin O)", "parameter": "IU/mL", "normalRange": "< 200"},
    {"name": "Rheumatoid Factor (RF)", "parameter": "IU/mL", "normalRange": "< 14"},
    {"name": "Antinuclear Antibody (ANA)", "parameter": "qualitative", "normalRange": "Negative"},
    {"name": "Brucella IgM/IgG", "parameter": "qualitative", "normalRange": "Negative/Positive"},
    {"name": "Malaria Antigen", "parameter": "qualitative", "normalRange": "Negative"},
    {"name": "Leptospira Serology", "parameter": "qualitative", "normalRange": "Negative"},
    {"name": "Chikungunya IgM/IgG", "parameter": "qualitative", "normalRange": "Negative/Positive"},
    {"name": "TORCH Panel", "parameter": "report", "normalRange": "Reference"},
    {"name": "HTLV 1/2", "parameter": "qualitative", "normalRange": "Negative"},
    {"name": "Strongyloides Serology", "parameter": "qualitative", "normalRange": "Negative"},
    {"name": "Rubella IgM/IgG", "parameter": "qualitative", "normalRange": "Negative/Positive"},
    {"name": "Hepatitis A IgM", "parameter": "qualitative", "normalRange": "Negative"}
  ],
  "Urine": [
    {"name": "Urine Routine Examination (R/E)", "parameter": "report", "normalRange": "Reference"},
    {"name": "Urine Microscopy", "parameter": "cells/uL", "normalRange": "0 - 5"},
    {"name": "Urine Culture & Sensitivity", "parameter": "report", "normalRange": "Reference"},
    {"name": "Urine pH", "parameter": "pH", "normalRange": "4.5 - 8.0"},
    {"name": "Urine Specific Gravity", "parameter": "", "normalRange": "1.005 - 1.030"},
    {"name": "Urine Protein", "parameter": "mg/dL", "normalRange": "Negative"},
    {"name": "Urine Microalbumin", "parameter": "mg/day", "normalRange": "< 30"},
    {"name": "Urine Creatinine", "parameter": "mg/dL", "normalRange": "Reference"},
    {"name": "Albumin/Creatinine Ratio (ACR)", "parameter": "mg/g", "normalRange": "< 30"},
    {"name": "Urine Sugar", "parameter": "mg/dL", "normalRange": "Negative"},
    {"name": "Urine Ketones", "parameter": "mg/dL", "normalRange": "Negative"},
    {"name": "Pregnancy Test (Urine hCG)", "parameter": "qualitative", "normalRange": "Negative/Positive"},
    {"name": "Urine Cytology", "parameter": "report", "normalRange": "Reference"},
    {"name": "24-hour Urine Protein", "parameter": "mg/day", "normalRange": "< 150"},
    {"name": "Urine Calcium", "parameter": "mg/day", "normalRange": "100 - 300"},
    {"name": "Urine Oxalate", "parameter": "mg/day", "normalRange": "10 - 40"},
    {"name": "Urine Sodium", "parameter": "mmol/L", "normalRange": "Reference"},
    {"name": "Urine Potassium", "parameter": "mmol/L", "normalRange": "Reference"},
    {"name": "Urine Chloride", "parameter": "mmol/L", "normalRange": "Reference"},
    {"name": "Urine Urobilinogen", "parameter": "mg/dL", "normalRange": "0.2 - 1.0"}
  ],
  "Stool": [
    {"name": "Stool Routine Examination (R/E)", "parameter": "report", "normalRange": "Reference"},
    {"name": "Stool Microscopy (Ova & Parasites)", "parameter": "report", "normalRange": "Reference"},
    {"name": "Fecal Occult Blood Test (FOBT)", "parameter": "ng/mL", "normalRange": "Negative"},
    {"name": "Stool Culture & Sensitivity", "parameter": "report", "normalRange": "Reference"},
    {"name": "Clostridium difficile Toxin", "parameter": "qualitative", "normalRange": "Negative"},
    {"name": "Stool Antigen - Giardia", "parameter": "qualitative", "normalRange": "Negative"},
    {"name": "Stool Antigen - H. pylori", "parameter": "qualitative", "normalRange": "Negative"},
    {"name": "Stool Macroscopy", "parameter": "report", "normalRange": "Reference"},
    {"name": "Calprotectin (fecal)", "parameter": "µg/g", "normalRange": "< 50"},
    {"name": "Stool PCR Panel", "parameter": "report", "normalRange": "Reference"},
    {"name": "Lactoferrin (fecal)", "parameter": "µg/g", "normalRange": "< 7.5"},
    {"name": "Stool Fat (Qualitative)", "parameter": "report", "normalRange": "Reference"},
    {"name": "Rotavirus Antigen", "parameter": "qualitative", "normalRange": "Negative"},
    {"name": "Enteric Pathogen PCR", "parameter": "report", "normalRange": "Reference"},
    {"name": "Cryptosporidium Antigen", "parameter": "qualitative", "normalRange": "Negative"},
    {"name": "Stool Adenovirus", "parameter": "qualitative", "normalRange": "Negative"},
    {"name": "Stool ELISA Pathogens", "parameter": "report", "normalRange": "Reference"},
    {"name": "Helminth Ova Screen", "parameter": "report", "normalRange": "Reference"},
    {"name": "Stool pH", "parameter": "pH", "normalRange": "5.5 - 7.5"},
    {"name": "Stool Reducing Substances", "parameter": "mg/dL", "normalRange": "Negative"}
  ],
  "Pathology": [
    {"name": "Histopathology - Biopsy (Skin)", "parameter": "report", "normalRange": "Reference"},
    {"name": "Histopathology - Biopsy (Liver)", "parameter": "report", "normalRange": "Reference"},
    {"name": "Histopathology - Biopsy (Colon)", "parameter": "report", "normalRange": "Reference"},
    {"name": "Histopathology - Biopsy (Prostate)", "parameter": "report", "normalRange": "Reference"},
    {"name": "Immunohistochemistry Panel", "parameter": "report", "normalRange": "Reference"},
    {"name": "FNAC Cytology", "parameter": "report", "normalRange": "Reference"},
    {"name": "Bone Marrow Biopsy", "parameter": "report", "normalRange": "Reference"},
    {"name": "Frozen Section", "parameter": "report", "normalRange": "Reference"},
    {"name": "Tumor Margin Assessment", "parameter": "report", "normalRange": "Reference"},
    {"name": "Peritoneal Fluid Cytology", "parameter": "report", "normalRange": "Reference"},
    {"name": "Pleural Fluid Cytology", "parameter": "report", "normalRange": "Reference"},
    {"name": "Surgical Pathology Report", "parameter": "report", "normalRange": "Reference"},
    {"name": "Special Stains (PAS/ZN)", "parameter": "report", "normalRange": "Reference"},
    {"name": "Molecular Pathology Panel", "parameter": "report", "normalRange": "Reference"},
    {"name": "Prostate Biopsy Gleason Score", "parameter": "report", "normalRange": "Reference"},
    {"name": "Lymph Node Biopsy Report", "parameter": "report", "normalRange": "Reference"},
    {"name": "Skin Punch Biopsy", "parameter": "report", "normalRange": "Reference"},
    {"name": "Renal Biopsy Report", "parameter": "report", "normalRange": "Reference"},
    {"name": "Histochemical Staining", "parameter": "report", "normalRange": "Reference"},
    {"name": "Pathology Consultation", "parameter": "report", "normalRange": "Reference"}
  ],
  "Endocrinology": [
    {"name": "Thyroid Stimulating Hormone (TSH)", "parameter": "µIU/mL", "normalRange": "0.4 - 4.0"},
    {"name": "Free T4", "parameter": "ng/dL", "normalRange": "0.8 - 1.8"},
    {"name": "Free T3", "parameter": "pg/mL", "normalRange": "2.3 - 4.2"},
    {"name": "Total T4", "parameter": "µg/dL", "normalRange": "5.0 - 12.0"},
    {"name": "Total T3", "parameter": "ng/dL", "normalRange": "80 - 200"},
    {"name": "Thyroid Peroxidase Antibodies (TPOAb)", "parameter": "IU/mL", "normalRange": "< 35"},
    {"name": "Thyroglobulin", "parameter": "ng/mL", "normalRange": "Reference"},
    {"name": "Insulin (Fasting)", "parameter": "µIU/mL", "normalRange": "2 - 25"},
    {"name": "C-Peptide", "parameter": "ng/mL", "normalRange": "0.5 - 2.0"},
    {"name": "Cortisol (Morning)", "parameter": "µg/dL", "normalRange": "5 - 25"},
    {"name": "Cortisol (Evening)", "parameter": "µg/dL", "normalRange": "2 - 14"},
    {"name": "Adrenocorticotropic Hormone (ACTH)", "parameter": "pg/mL", "normalRange": "10 - 60"},
    {"name": "Growth Hormone", "parameter": "ng/mL", "normalRange": "< 10"},
    {"name": "Prolactin", "parameter": "ng/mL", "normalRange": "5 - 25"},
    {"name": "Parathyroid Hormone (PTH)", "parameter": "pg/mL", "normalRange": "15 - 65"},
    {"name": "Calcitonin", "parameter": "pg/mL", "normalRange": "< 10"},
    {"name": "Vitamin D (25-OH)", "parameter": "ng/mL", "normalRange": "30 - 100"},
    {"name": "Vitamin B12", "parameter": "pg/mL", "normalRange": "200 - 900"},
    {"name": "Testosterone (Male)", "parameter": "ng/dL", "normalRange": "300 - 1000"},
    {"name": "Estradiol (Female)", "parameter": "pg/mL", "normalRange": "30 - 400"}
  ]
};