// Auto-generated Test Data
window.testData = {
  "Hematology": [
    { "name": "Hematology Test A", "parameter": "ng/mL", "normalRange": "70 - 100" },
    { "name": "Hematology Test B", "parameter": "mg/dL", "normalRange": "0 - 5" },
    { "name": "Hematology Test C", "parameter": "mg/dL", "normalRange": "0 - 5" },
    { "name": "Hematology Test D", "parameter": "IU/L", "normalRange": "3.5 - 5.5" },
    { "name": "Hematology Test E", "parameter": "cells/uL", "normalRange": "90 - 120" },
    { "name": "Hematology Test F", "parameter": "mm/hr", "normalRange": "10 - 40" },
    { "name": "Hematology Test G", "parameter": "mm/hr", "normalRange": "12 - 16" },
    { "name": "Hematology Test H", "parameter": "mg/dL", "normalRange": "70 - 100" },
    { "name": "Hematology Test I", "parameter": "g/dL", "normalRange": "150 - 450" },
    { "name": "Hematology Test J", "parameter": "mmol/L", "normalRange": "0 - 20" },
    { "name": "Hematology Test K", "parameter": "mg/dL", "normalRange": "90 - 120" },
    { "name": "Hematology Test L", "parameter": "ng/mL", "normalRange": "0 - 5" },
    { "name": "Hematology Test M", "parameter": "ng/mL", "normalRange": "0 - 20" },
    { "name": "Hematology Test N", "parameter": "mg/dL", "normalRange": "150 - 450" },
    { "name": "Hematology Test O", "parameter": "g/dL", "normalRange": "0 - 5" },
    { "name": "Hematology Test P", "parameter": "ng/mL", "normalRange": "70 - 100" },
    { "name": "Hematology Test Q", "parameter": "ng/mL", "normalRange": "150 - 450" },
    { "name": "Hematology Test R", "parameter": "g/dL", "normalRange": "150 - 450" },
    { "name": "Hematology Test S", "parameter": "IU/L", "normalRange": "0 - 5" },
    { "name": "Hematology Test T", "parameter": "IU/L", "normalRange": "70 - 100" }
  ],
  "Biochemistry": [
    { "name": "Biochemistry Test A", "parameter": "IU/L", "normalRange": "12 - 16" },
    { "name": "Biochemistry Test B", "parameter": "ng/mL", "normalRange": "150 - 450" },
    { "name": "Biochemistry Test C", "parameter": "mmol/L", "normalRange": "150 - 450" },
    { "name": "Biochemistry Test D", "parameter": "mm/hr", "normalRange": "10 - 40" },
    { "name": "Biochemistry Test E", "parameter": "g/dL", "normalRange": "10 - 40" },
    { "name": "Biochemistry Test F", "parameter": "g/dL", "normalRange": "0.5 - 2.0" },
    { "name": "Biochemistry Test G", "parameter": "mg/dL", "normalRange": "12 - 16" },
    { "name": "Biochemistry Test H", "parameter": "cells/uL", "normalRange": "0 - 5" },
    { "name": "Biochemistry Test I", "parameter": "g/dL", "normalRange": "150 - 450" },
    { "name": "Biochemistry Test J", "parameter": "g/dL", "normalRange": "90 - 120" },
    { "name": "Biochemistry Test K", "parameter": "mm/hr", "normalRange": "10 - 40" },
    { "name": "Biochemistry Test L", "parameter": "mg/dL", "normalRange": "0 - 5" },
    { "name": "Biochemistry Test M", "parameter": "ng/mL", "normalRange": "150 - 450" },
    { "name": "Biochemistry Test N", "parameter": "mg/dL", "normalRange": "12 - 16" },
    { "name": "Biochemistry Test O", "parameter": "mmol/L", "normalRange": "90 - 120" },
    { "name": "Biochemistry Test P", "parameter": "ng/mL", "normalRange": "3.5 - 5.5" },
    { "name": "Biochemistry Test Q", "parameter": "g/dL", "normalRange": "0 - 20" },
    { "name": "Biochemistry Test R", "parameter": "IU/L", "normalRange": "10 - 40" },
    { "name": "Biochemistry Test S", "parameter": "mg/dL", "normalRange": "150 - 450" },
    { "name": "Biochemistry Test T", "parameter": "mm/hr", "normalRange": "3.5 - 5.5" }
  ],
  "Serology": [
    { "name": "Serology Test A", "parameter": "ng/mL", "normalRange": "0 - 20" },
    { "name": "Serology Test B", "parameter": "ng/mL", "normalRange": "70 - 100" },
    { "name": "Serology Test C", "parameter": "IU/L", "normalRange": "0.5 - 2.0" },
    { "name": "Serology Test D", "parameter": "IU/L", "normalRange": "12 - 16" },
    { "name": "Serology Test E", "parameter": "cells/uL", "normalRange": "0 - 20" },
    { "name": "Serology Test F", "parameter": "g/dL", "normalRange": "0 - 20" },
    { "name": "Serology Test G", "parameter": "mmol/L", "normalRange": "12 - 16" },
    { "name": "Serology Test H", "parameter": "mg/dL", "normalRange": "12 - 16" },
    { "name": "Serology Test I", "parameter": "IU/L", "normalRange": "10 - 40" },
    { "name": "Serology Test J", "parameter": "g/dL", "normalRange": "70 - 100" },
    { "name": "Serology Test K", "parameter": "mmol/L", "normalRange": "20 - 200" },
    { "name": "Serology Test L", "parameter": "mg/dL", "normalRange": "90 - 120" },
    { "name": "Serology Test M", "parameter": "ng/mL", "normalRange": "0 - 20" },
    { "name": "Serology Test N", "parameter": "mg/dL", "normalRange": "150 - 450" },
    { "name": "Serology Test O", "parameter": "cells/uL", "normalRange": "12 - 16" },
    { "name": "Serology Test P", "parameter": "mmol/L", "normalRange": "70 - 100" },
    { "name": "Serology Test Q", "parameter": "cells/uL", "normalRange": "10 - 40" },
    { "name": "Serology Test R", "parameter": "mmol/L", "normalRange": "70 - 100" },
    { "name": "Serology Test S", "parameter": "ng/mL", "normalRange": "0 - 5" },
    { "name": "Serology Test T", "parameter": "mm/hr", "normalRange": "12 - 16" }
  ],
  "Microbiology": [
    { "name": "Microbiology Test A", "parameter": "IU/L", "normalRange": "0.5 - 2.0" },
    { "name": "Microbiology Test B", "parameter": "IU/L", "normalRange": "10 - 40" },
    { "name": "Microbiology Test C", "parameter": "cells/uL", "normalRange": "90 - 120" },
    { "name": "Microbiology Test D", "parameter": "mg/dL", "normalRange": "10 - 40" },
    { "name": "Microbiology Test E", "parameter": "mm/hr", "normalRange": "10 - 40" },
    { "name": "Microbiology Test F", "parameter": "mm/hr", "normalRange": "70 - 100" },
    { "name": "Microbiology Test G", "parameter": "ng/mL", "normalRange": "70 - 100" },
    { "name": "Microbiology Test H", "parameter": "IU/L", "normalRange": "90 - 120" },
    { "name": "Microbiology Test I", "parameter": "mmol/L", "normalRange": "10 - 40" },
    { "name": "Microbiology Test J", "parameter": "ng/mL", "normalRange": "10 - 40" },
    { "name": "Microbiology Test K", "parameter": "g/dL", "normalRange": "150 - 450" },
    { "name": "Microbiology Test L", "parameter": "ng/mL", "normalRange": "0.5 - 2.0" },
    { "name": "Microbiology Test M", "parameter": "mmol/L", "normalRange": "0.5 - 2.0" },
    { "name": "Microbiology Test N", "parameter": "g/dL", "normalRange": "3.5 - 5.5" },
    { "name": "Microbiology Test O", "parameter": "g/dL", "normalRange": "12 - 16" },
    { "name": "Microbiology Test P", "parameter": "mg/dL", "normalRange": "150 - 450" },
    { "name": "Microbiology Test Q", "parameter": "mm/hr", "normalRange": "10 - 40" },
    { "name": "Microbiology Test R", "parameter": "mmol/L", "normalRange": "10 - 40" },
    { "name": "Microbiology Test S", "parameter": "mg/dL", "normalRange": "90 - 120" },
    { "name": "Microbiology Test T", "parameter": "mmol/L", "normalRange": "70 - 100" }
  ],
  "Urine": [
    { "name": "Urine Test A", "parameter": "mm/hr", "normalRange": "70 - 100" },
    { "name": "Urine Test B", "parameter": "g/dL", "normalRange": "12 - 16" },
    { "name": "Urine Test C", "parameter": "IU/L", "normalRange": "10 - 40" },
    { "name": "Urine Test D", "parameter": "mg/dL", "normalRange": "0 - 5" },
    { "name": "Urine Test E", "parameter": "mg/dL", "normalRange": "20 - 200" },
    { "name": "Urine Test F", "parameter": "mg/dL", "normalRange": "3.5 - 5.5" },
    { "name": "Urine Test G", "parameter": "cells/uL", "normalRange": "0.5 - 2.0" },
    { "name": "Urine Test H", "parameter": "mmol/L", "normalRange": "3.5 - 5.5" },
    { "name": "Urine Test I", "parameter": "IU/L", "normalRange": "150 - 450" },
    { "name": "Urine Test J", "parameter": "cells/uL", "normalRange": "150 - 450" },
    { "name": "Urine Test K", "parameter": "IU/L", "normalRange": "150 - 450" },
    { "name": "Urine Test L", "parameter": "g/dL", "normalRange": "70 - 100" },
    { "name": "Urine Test M", "parameter": "ng/mL", "normalRange": "70 - 100" },
    { "name": "Urine Test N", "parameter": "cells/uL", "normalRange": "10 - 40" },
    { "name": "Urine Test O", "parameter": "mmol/L", "normalRange": "20 - 200" },
    { "name": "Urine Test P", "parameter": "IU/L", "normalRange": "70 - 100" },
    { "name": "Urine Test Q", "parameter": "ng/mL", "normalRange": "0 - 5" },
    { "name": "Urine Test R", "parameter": "g/dL", "normalRange": "10 - 40" },
    { "name": "Urine Test S", "parameter": "ng/mL", "normalRange": "0 - 20" },
    { "name": "Urine Test T", "parameter": "cells/uL", "normalRange": "90 - 120" }
  ],
  "Stool": [
    { "name": "Stool Test A", "parameter": "ng/mL", "normalRange": "70 - 100" },
    { "name": "Stool Test B", "parameter": "cells/uL", "normalRange": "0 - 5" },
    { "name": "Stool Test C", "parameter": "ng/mL", "normalRange": "3.5 - 5.5" },
    { "name": "Stool Test D", "parameter": "mg/dL", "normalRange": "3.5 - 5.5" },
    { "name": "Stool Test E", "parameter": "cells/uL", "normalRange": "150 - 450" },
    { "name": "Stool Test F", "parameter": "g/dL", "normalRange": "150 - 450" },
    { "name": "Stool Test G", "parameter": "g/dL", "normalRange": "10 - 40" },
    { "name": "Stool Test H", "parameter": "mg/dL", "normalRange": "90 - 120" },
    { "name": "Stool Test I", "parameter": "ng/mL", "normalRange": "150 - 450" },
    { "name": "Stool Test J", "parameter": "mg/dL", "normalRange": "12 - 16" },
    { "name": "Stool Test K", "parameter": "mg/dL", "normalRange": "10 - 40" },
    { "name": "Stool Test L", "parameter": "mg/dL", "normalRange": "90 - 120" },
    { "name": "Stool Test M", "parameter": "mm/hr", "normalRange": "0.5 - 2.0" },
    { "name": "Stool Test N", "parameter": "g/dL", "normalRange": "90 - 120" },
    { "name": "Stool Test O", "parameter": "ng/mL", "normalRange": "0.5 - 2.0" },
    { "name": "Stool Test P", "parameter": "g/dL", "normalRange": "10 - 40" },
    { "name": "Stool Test Q", "parameter": "mm/hr", "normalRange": "10 - 40" },
    { "name": "Stool Test R", "parameter": "mg/dL", "normalRange": "0.5 - 2.0" },
    { "name": "Stool Test S", "parameter": "mg/dL", "normalRange": "0 - 20" },
    { "name": "Stool Test T", "parameter": "mmol/L", "normalRange": "20 - 200" }
  ],
  "Immunology": [
    { "name": "Immunology Test A", "parameter": "g/dL", "normalRange": "3.5 - 5.5" },
    { "name": "Immunology Test B", "parameter": "mg/dL", "normalRange": "12 - 16" },
    { "name": "Immunology Test C", "parameter": "mg/dL", "normalRange": "0 - 20" },
    { "name": "Immunology Test D", "parameter": "mm/hr", "normalRange": "20 - 200" },
    { "name": "Immunology Test E", "parameter": "ng/mL", "normalRange": "12 - 16" },
    { "name": "Immunology Test F", "parameter": "mg/dL", "normalRange": "150 - 450" },
    { "name": "Immunology Test G", "parameter": "cells/uL", "normalRange": "0.5 - 2.0" },
    { "name": "Immunology Test H", "parameter": "mm/hr", "normalRange": "10 - 40" },
    { "name": "Immunology Test I", "parameter": "mm/hr", "normalRange": "0 - 20" },
    { "name": "Immunology Test J", "parameter": "mm/hr", "normalRange": "10 - 40" },
    { "name": "Immunology Test K", "parameter": "mmol/L", "normalRange": "0 - 20" },
    { "name": "Immunology Test L", "parameter": "g/dL", "normalRange": "90 - 120" },
    { "name": "Immunology Test M", "parameter": "IU/L", "normalRange": "90 - 120" },
    { "name": "Immunology Test N", "parameter": "ng/mL", "normalRange": "12 - 16" },
    { "name": "Immunology Test O", "parameter": "ng/mL", "normalRange": "10 - 40" },
    { "name": "Immunology Test P", "parameter": "IU/L", "normalRange": "0 - 5" },
    { "name": "Immunology Test Q", "parameter": "mm/hr", "normalRange": "3.5 - 5.5" },
    { "name": "Immunology Test R", "parameter": "cells/uL", "normalRange": "12 - 16" },
    { "name": "Immunology Test S", "parameter": "mmol/L", "normalRange": "0.5 - 2.0" },
    { "name": "Immunology Test T", "parameter": "cells/uL", "normalRange": "0 - 20" }
  ],
  "Pathology": [
    { "name": "Pathology Test A", "parameter": "cells/uL", "normalRange": "0 - 20" },
    { "name": "Pathology Test B", "parameter": "ng/mL", "normalRange": "150 - 450" },
    { "name": "Pathology Test C", "parameter": "mg/dL", "normalRange": "3.5 - 5.5" },
    { "name": "Pathology Test D", "parameter": "mmol/L", "normalRange": "90 - 120" },
    { "name": "Pathology Test E", "parameter": "ng/mL", "normalRange": "0.5 - 2.0" },
    { "name": "Pathology Test F", "parameter": "mg/dL", "normalRange": "70 - 100" },
    { "name": "Pathology Test G", "parameter": "mmol/L", "normalRange": "0.5 - 2.0" },
    { "name": "Pathology Test H", "parameter": "mg/dL", "normalRange": "3.5 - 5.5" },
    { "name": "Pathology Test I", "parameter": "mm/hr", "normalRange": "20 - 200" },
    { "name": "Pathology Test J", "parameter": "mg/dL", "normalRange": "90 - 120" },
    { "name": "Pathology Test K", "parameter": "mmol/L", "normalRange": "70 - 100" },
    { "name": "Pathology Test L", "parameter": "mm/hr", "normalRange": "150 - 450" },
    { "name": "Pathology Test M", "parameter": "ng/mL", "normalRange": "10 - 40" },
    { "name": "Pathology Test N", "parameter": "mm/hr", "normalRange": "70 - 100" },
    { "name": "Pathology Test O", "parameter": "mg/dL", "normalRange": "90 - 120" },
    { "name": "Pathology Test P", "parameter": "ng/mL", "normalRange": "20 - 200" },
    { "name": "Pathology Test Q", "parameter": "ng/mL", "normalRange": "150 - 450" },
    { "name": "Pathology Test R", "parameter": "g/dL", "normalRange": "0.5 - 2.0" },
    { "name": "Pathology Test S", "parameter": "mg/dL", "normalRange": "0 - 5" },
    { "name": "Pathology Test T", "parameter": "g/dL", "normalRange": "12 - 16" }
  ],
  "Endocrinology": [
    { "name": "Endocrinology Test A", "parameter": "ng/mL", "normalRange": "0 - 5" },
    { "name": "Endocrinology Test B", "parameter": "mm/hr", "normalRange": "12 - 16" },
    { "name": "Endocrinology Test C", "parameter": "cells/uL", "normalRange": "150 - 450" },
    { "name": "Endocrinology Test D", "parameter": "mg/dL", "normalRange": "90 - 120" },
    { "name": "Endocrinology Test E", "parameter": "ng/mL", "normalRange": "3.5 - 5.5" },
    { "name": "Endocrinology Test F", "parameter": "mg/dL", "normalRange": "3.5 - 5.5" },
    { "name": "Endocrinology Test G", "parameter": "IU/L", "normalRange": "12 - 16" },
    { "name": "Endocrinology Test H", "parameter": "g/dL", "normalRange": "12 - 16" },
    { "name": "Endocrinology Test I", "parameter": "ng/mL", "normalRange": "90 - 120" },
    { "name": "Endocrinology Test J", "parameter": "IU/L", "normalRange": "3.5 - 5.5" },
    { "name": "Endocrinology Test K", "parameter": "mg/dL", "normalRange": "70 - 100" },
    { "name": "Endocrinology Test L", "parameter": "g/dL", "normalRange": "150 - 450" },
    { "name": "Endocrinology Test M", "parameter": "mg/dL", "normalRange": "150 - 450" },
    { "name": "Endocrinology Test N", "parameter": "mmol/L", "normalRange": "12 - 16" },
    { "name": "Endocrinology Test O", "parameter": "IU/L", "normalRange": "3.5 - 5.5" },
    { "name": "Endocrinology Test P", "parameter": "g/dL", "normalRange": "0 - 20" },
    { "name": "Endocrinology Test Q", "parameter": "ng/mL", "normalRange": "0.5 - 2.0" },
    { "name": "Endocrinology Test R", "parameter": "ng/mL", "normalRange": "10 - 40" },
    { "name": "Endocrinology Test S", "parameter": "cells/uL", "normalRange": "150 - 450" },
    { "name": "Endocrinology Test T", "parameter": "mm/hr", "normalRange": "90 - 120" }
  ],
  "Toxicology": [
    { "name": "Toxicology Test A", "parameter": "mmol/L", "normalRange": "12 - 16" },
    { "name": "Toxicology Test B", "parameter": "cells/uL", "normalRange": "90 - 120" },
    { "name": "Toxicology Test C", "parameter": "cells/uL", "normalRange": "10 - 40" },
    { "name": "Toxicology Test D", "parameter": "IU/L", "normalRange": "12 - 16" },
    { "name": "Toxicology Test E", "parameter": "cells/uL", "normalRange": "0 - 20" },
    { "name": "Toxicology Test F", "parameter": "cells/uL", "normalRange": "70 - 100" },
    { "name": "Toxicology Test G", "parameter": "mmol/L", "normalRange": "20 - 200" },
    { "name": "Toxicology Test H", "parameter": "cells/uL", "normalRange": "70 - 100" },
    { "name": "Toxicology Test I", "parameter": "mmol/L", "normalRange": "3.5 - 5.5" },
    { "name": "Toxicology Test J", "parameter": "cells/uL", "normalRange": "0 - 20" },
    { "name": "Toxicology Test K", "parameter": "mmol/L", "normalRange": "0 - 5" },
    { "name": "Toxicology Test L", "parameter": "mm/hr", "normalRange": "10 - 40" },
    { "name": "Toxicology Test M", "parameter": "mmol/L", "normalRange": "0 - 20" },
    { "name": "Toxicology Test N", "parameter": "IU/L", "normalRange": "12 - 16" },
    { "name": "Toxicology Test O", "parameter": "cells/uL", "normalRange": "150 - 450" },
    { "name": "Toxicology Test P", "parameter": "ng/mL", "normalRange": "0 - 20" },
    { "name": "Toxicology Test Q", "parameter": "g/dL", "normalRange": "10 - 40" },
    { "name": "Toxicology Test R", "parameter": "IU/L", "normalRange": "90 - 120" },
    { "name": "Toxicology Test S", "parameter": "cells/uL", "normalRange": "0 - 20" },
    { "name": "Toxicology Test T", "parameter": "mmol/L", "normalRange": "12 - 16" }
  ],
  "Molecular Biology": [
    { "name": "Molecular Biology Test A", "parameter": "mmol/L", "normalRange": "10 - 40" },
    { "name": "Molecular Biology Test B", "parameter": "mm/hr", "normalRange": "3.5 - 5.5" },
    { "name": "Molecular Biology Test C", "parameter": "cells/uL", "normalRange": "3.5 - 5.5" },
    { "name": "Molecular Biology Test D", "parameter": "g/dL", "normalRange": "3.5 - 5.5" },
    { "name": "Molecular Biology Test E", "parameter": "mg/dL", "normalRange": "20 - 200" },
    { "name": "Molecular Biology Test F", "parameter": "cells/uL", "normalRange": "150 - 450" },
    { "name": "Molecular Biology Test G", "parameter": "cells/uL", "normalRange": "0 - 20" },
    { "name": "Molecular Biology Test H", "parameter": "g/dL", "normalRange": "90 - 120" },
    { "name": "Molecular Biology Test I", "parameter": "mm/hr", "normalRange": "3.5 - 5.5" },
    { "name": "Molecular Biology Test J", "parameter": "mmol/L", "normalRange": "0 - 20" },
    { "name": "Molecular Biology Test K", "parameter": "IU/L", "normalRange": "70 - 100" },
    { "name": "Molecular Biology Test L", "parameter": "mg/dL", "normalRange": "150 - 450" },
    { "name": "Molecular Biology Test M", "parameter": "mmol/L", "normalRange": "0.5 - 2.0" },
    { "name": "Molecular Biology Test N", "parameter": "mg/dL", "normalRange": "0 - 20" },
    { "name": "Molecular Biology Test O", "parameter": "mg/dL", "normalRange": "12 - 16" },
    { "name": "Molecular Biology Test P", "parameter": "mg/dL", "normalRange": "0.5 - 2.0" },
    { "name": "Molecular Biology Test Q", "parameter": "cells/uL", "normalRange": "0 - 5" },
    { "name": "Molecular Biology Test R", "parameter": "g/dL", "normalRange": "0.5 - 2.0" },
    { "name": "Molecular Biology Test S", "parameter": "cells/uL", "normalRange": "150 - 450" },
    { "name": "Molecular Biology Test T", "parameter": "mm/hr", "normalRange": "3.5 - 5.5" }
  ],
  "Virology": [
    { "name": "Virology Test A", "parameter": "ng/mL", "normalRange": "150 - 450" },
    { "name": "Virology Test B", "parameter": "cells/uL", "normalRange": "0.5 - 2.0" },
    { "name": "Virology Test C", "parameter": "IU/L", "normalRange": "12 - 16" },
    { "name": "Virology Test D", "parameter": "g/dL", "normalRange": "12 - 16" },
    { "name": "Virology Test E", "parameter": "IU/L", "normalRange": "90 - 120" },
    { "name": "Virology Test F", "parameter": "g/dL", "normalRange": "20 - 200" },
    { "name": "Virology Test G", "parameter": "mg/dL", "normalRange": "90 - 120" },
    { "name": "Virology Test H", "parameter": "mm/hr", "normalRange": "0 - 20" },
    { "name": "Virology Test I", "parameter": "mm/hr", "normalRange": "70 - 100" },
    { "name": "Virology Test J", "parameter": "mm/hr", "normalRange": "0 - 20" },
    { "name": "Virology Test K", "parameter": "g/dL", "normalRange": "12 - 16" },
    { "name": "Virology Test L", "parameter": "IU/L", "normalRange": "0 - 5" },
    { "name": "Virology Test M", "parameter": "g/dL", "normalRange": "150 - 450" },
    { "name": "Virology Test N", "parameter": "mg/dL", "normalRange": "70 - 100" },
    { "name": "Virology Test O", "parameter": "g/dL", "normalRange": "10 - 40" },
    { "name": "Virology Test P", "parameter": "ng/mL", "normalRange": "10 - 40" },
    { "name": "Virology Test Q", "parameter": "ng/mL", "normalRange": "0 - 20" },
    { "name": "Virology Test R", "parameter": "cells/uL", "normalRange": "70 - 100" },
    { "name": "Virology Test S", "parameter": "mm/hr", "normalRange": "0.5 - 2.0" },
    { "name": "Virology Test T", "parameter": "mg/dL", "normalRange": "0 - 5" }
  ],
  "Parasitology": [
    { "name": "Parasitology Test A", "parameter": "mg/dL", "normalRange": "70 - 100" },
    { "name": "Parasitology Test B", "parameter": "cells/uL", "normalRange": "0 - 20" },
    { "name": "Parasitology Test C", "parameter": "g/dL", "normalRange": "0.5 - 2.0" },
    { "name": "Parasitology Test D", "parameter": "cells/uL", "normalRange": "70 - 100" },
    { "name": "Parasitology Test E", "parameter": "IU/L", "normalRange": "3.5 - 5.5" },
    { "name": "Parasitology Test F", "parameter": "mmol/L", "normalRange": "12 - 16" },
    { "name": "Parasitology Test G", "parameter": "mg/dL", "normalRange": "12 - 16" },
    { "name": "Parasitology Test H", "parameter": "IU/L", "normalRange": "0 - 20" },
    { "name": "Parasitology Test I", "parameter": "g/dL", "normalRange": "70 - 100" },
    { "name": "Parasitology Test J", "parameter": "mmol/L", "normalRange": "10 - 40" },
    { "name": "Parasitology Test K", "parameter": "mg/dL", "normalRange": "0 - 5" },
    { "name": "Parasitology Test L", "parameter": "g/dL", "normalRange": "70 - 100" },
    { "name": "Parasitology Test M", "parameter": "ng/mL", "normalRange": "3.5 - 5.5" },
    { "name": "Parasitology Test N", "parameter": "mg/dL", "normalRange": "3.5 - 5.5" },
    { "name": "Parasitology Test O", "parameter": "IU/L", "normalRange": "12 - 16" },
    { "name": "Parasitology Test P", "parameter": "mg/dL", "normalRange": "150 - 450" },
    { "name": "Parasitology Test Q", "parameter": "mmol/L", "normalRange": "0.5 - 2.0" },
    { "name": "Parasitology Test R", "parameter": "mm/hr", "normalRange": "10 - 40" },
    { "name": "Parasitology Test S", "parameter": "mmol/L", "normalRange": "0.5 - 2.0" },
    { "name": "Parasitology Test T", "parameter": "IU/L", "normalRange": "150 - 450" }
  ],
  "Histopathology": [
    { "name": "Histopathology Test A", "parameter": "cells/uL", "normalRange": "20 - 200" },
    { "name": "Histopathology Test B", "parameter": "IU/L", "normalRange": "3.5 - 5.5" },
    { "name": "Histopathology Test C", "parameter": "mm/hr", "normalRange": "70 - 100" },
    { "name": "Histopathology Test D", "parameter": "mg/dL", "normalRange": "70 - 100" },
    { "name": "Histopathology Test E", "parameter": "g/dL", "normalRange": "150 - 450" },
    { "name": "Histopathology Test F", "parameter": "mg/dL", "normalRange": "90 - 120" },
    { "name": "Histopathology Test G", "parameter": "ng/mL", "normalRange": "0.5 - 2.0" },
    { "name": "Histopathology Test H", "parameter": "mmol/L", "normalRange": "0 - 20" },
    { "name": "Histopathology Test I", "parameter": "cells/uL", "normalRange": "70 - 100" },
    { "name": "Histopathology Test J", "parameter": "mg/dL", "normalRange": "3.5 - 5.5" },
    { "name": "Histopathology Test K", "parameter": "mg/dL", "normalRange": "150 - 450" },
    { "name": "Histopathology Test L", "parameter": "mg/dL", "normalRange": "70 - 100" },
    { "name": "Histopathology Test M", "parameter": "mg/dL", "normalRange": "70 - 100" },
    { "name": "Histopathology Test N", "parameter": "g/dL", "normalRange": "150 - 450" },
    { "name": "Histopathology Test O", "parameter": "mm/hr", "normalRange": "0.5 - 2.0" },
    { "name": "Histopathology Test P", "parameter": "IU/L", "normalRange": "90 - 120" },
    { "name": "Histopathology Test Q", "parameter": "g/dL", "normalRange": "150 - 450" },
    { "name": "Histopathology Test R", "parameter": "cells/uL", "normalRange": "12 - 16" },
    { "name": "Histopathology Test S", "parameter": "cells/uL", "normalRange": "0.5 - 2.0" },
    { "name": "Histopathology Test T", "parameter": "mg/dL", "normalRange": "0 - 20" }
  ],
  "Genetics": [
    { "name": "Genetics Test A", "parameter": "ng/mL", "normalRange": "70 - 100" },
    { "name": "Genetics Test B", "parameter": "g/dL", "normalRange": "0 - 5" },
    { "name": "Genetics Test C", "parameter": "mm/hr", "normalRange": "0.5 - 2.0" },
    { "name": "Genetics Test D", "parameter": "IU/L", "normalRange": "10 - 40" },
    { "name": "Genetics Test E", "parameter": "mm/hr", "normalRange": "0 - 5" },
    { "name": "Genetics Test F", "parameter": "ng/mL", "normalRange": "150 - 450" },
    { "name": "Genetics Test G", "parameter": "IU/L", "normalRange": "150 - 450" },
    { "name": "Genetics Test H", "parameter": "cells/uL", "normalRange": "70 - 100" },
    { "name": "Genetics Test I", "parameter": "g/dL", "normalRange": "0 - 20" },
    { "name": "Genetics Test J", "parameter": "mmol/L", "normalRange": "70 - 100" },
    { "name": "Genetics Test K", "parameter": "cells/uL", "normalRange": "10 - 40" },
    { "name": "Genetics Test L", "parameter": "IU/L", "normalRange": "3.5 - 5.5" },
    { "name": "Genetics Test M", "parameter": "mmol/L", "normalRange": "3.5 - 5.5" },
    { "name": "Genetics Test N", "parameter": "ng/mL", "normalRange": "10 - 40" },
    { "name": "Genetics Test O", "parameter": "g/dL", "normalRange": "12 - 16" },
    { "name": "Genetics Test P", "parameter": "IU/L", "normalRange": "150 - 450" },
    { "name": "Genetics Test Q", "parameter": "cells/uL", "normalRange": "70 - 100" },
    { "name": "Genetics Test R", "parameter": "cells/uL", "normalRange": "3.5 - 5.5" },
    { "name": "Genetics Test S", "parameter": "mmol/L", "normalRange": "70 - 100" },
    { "name": "Genetics Test T", "parameter": "mmol/L", "normalRange": "3.5 - 5.5" }
  ],
  "Oncology": [
    { "name": "Oncology Test A", "parameter": "mmol/L", "normalRange": "150 - 450" },
    { "name": "Oncology Test B", "parameter": "mm/hr", "normalRange": "0 - 5" },
    { "name": "Oncology Test C", "parameter": "mg/dL", "normalRange": "0 - 5" },
    { "name": "Oncology Test D", "parameter": "ng/mL", "normalRange": "0 - 5" },
    { "name": "Oncology Test E", "parameter": "ng/mL", "normalRange": "0.5 - 2.0" },
    { "name": "Oncology Test F", "parameter": "ng/mL", "normalRange": "3.5 - 5.5" },
    { "name": "Oncology Test G", "parameter": "mm/hr", "normalRange": "10 - 40" },
    { "name": "Oncology Test H", "parameter": "mg/dL", "normalRange": "90 - 120" },
    { "name": "Oncology Test I", "parameter": "mm/hr", "normalRange": "10 - 40" },
    { "name": "Oncology Test J", "parameter": "mg/dL", "normalRange": "150 - 450" },
    { "name": "Oncology Test K", "parameter": "ng/mL", "normalRange": "20 - 200" },
    { "name": "Oncology Test L", "parameter": "ng/mL", "normalRange": "10 - 40" },
    { "name": "Oncology Test M", "parameter": "IU/L", "normalRange": "20 - 200" },
    { "name": "Oncology Test N", "parameter": "g/dL", "normalRange": "0.5 - 2.0" },
    { "name": "Oncology Test O", "parameter": "g/dL", "normalRange": "12 - 16" },
    { "name": "Oncology Test P", "parameter": "IU/L", "normalRange": "0 - 5" },
    { "name": "Oncology Test Q", "parameter": "mm/hr", "normalRange": "3.5 - 5.5" },
    { "name": "Oncology Test R", "parameter": "ng/mL", "normalRange": "12 - 16" },
    { "name": "Oncology Test S", "parameter": "mm/hr", "normalRange": "90 - 120" },
    { "name": "Oncology Test T", "parameter": "g/dL", "normalRange": "150 - 450" }
  ],
  "Allergy Testing": [
    { "name": "Allergy Testing Test A", "parameter": "mm/hr", "normalRange": "0 - 5" },
    { "name": "Allergy Testing Test B", "parameter": "IU/L", "normalRange": "0 - 20" },
    { "name": "Allergy Testing Test C", "parameter": "ng/mL", "normalRange": "10 - 40" },
    { "name": "Allergy Testing Test D", "parameter": "ng/mL", "normalRange": "20 - 200" },
    { "name": "Allergy Testing Test E", "parameter": "mg/dL", "normalRange": "3.5 - 5.5" },
    { "name": "Allergy Testing Test F", "parameter": "mmol/L", "normalRange": "10 - 40" },
    { "name": "Allergy Testing Test G", "parameter": "mmol/L", "normalRange": "90 - 120" },
    { "name": "Allergy Testing Test H", "parameter": "mg/dL", "normalRange": "20 - 200" },
    { "name": "Allergy Testing Test I", "parameter": "g/dL", "normalRange": "12 - 16" },
    { "name": "Allergy Testing Test J", "parameter": "mmol/L", "normalRange": "10 - 40" },
    { "name": "Allergy Testing Test K", "parameter": "IU/L", "normalRange": "90 - 120" },
    { "name": "Allergy Testing Test L", "parameter": "ng/mL", "normalRange": "3.5 - 5.5" },
    { "name": "Allergy Testing Test M", "parameter": "mm/hr", "normalRange": "0 - 20" },
    { "name": "Allergy Testing Test N", "parameter": "IU/L", "normalRange": "0.5 - 2.0" },
    { "name": "Allergy Testing Test O", "parameter": "mm/hr", "normalRange": "3.5 - 5.5" },
    { "name": "Allergy Testing Test P", "parameter": "mm/hr", "normalRange": "0 - 5" },
    { "name": "Allergy Testing Test Q", "parameter": "cells/uL", "normalRange": "12 - 16" },
    { "name": "Allergy Testing Test R", "parameter": "cells/uL", "normalRange": "3.5 - 5.5" },
    { "name": "Allergy Testing Test S", "parameter": "ng/mL", "normalRange": "3.5 - 5.5" },
    { "name": "Allergy Testing Test T", "parameter": "ng/mL", "normalRange": "20 - 200" }
  ],
  "Blood Bank": [
    { "name": "Blood Bank Test A", "parameter": "mmol/L", "normalRange": "70 - 100" },
    { "name": "Blood Bank Test B", "parameter": "IU/L", "normalRange": "3.5 - 5.5" },
    { "name": "Blood Bank Test C", "parameter": "mm/hr", "normalRange": "3.5 - 5.5" },
    { "name": "Blood Bank Test D", "parameter": "g/dL", "normalRange": "10 - 40" },
    { "name": "Blood Bank Test E", "parameter": "cells/uL", "normalRange": "0 - 5" },
    { "name": "Blood Bank Test F", "parameter": "g/dL", "normalRange": "3.5 - 5.5" },
    { "name": "Blood Bank Test G", "parameter": "mmol/L", "normalRange": "70 - 100" },
    { "name": "Blood Bank Test H", "parameter": "mg/dL", "normalRange": "0 - 20" },
    { "name": "Blood Bank Test I", "parameter": "ng/mL", "normalRange": "12 - 16" },
    { "name": "Blood Bank Test J", "parameter": "cells/uL", "normalRange": "20 - 200" },
    { "name": "Blood Bank Test K", "parameter": "mg/dL", "normalRange": "0 - 5" },
    { "name": "Blood Bank Test L", "parameter": "mmol/L", "normalRange": "20 - 200" },
    { "name": "Blood Bank Test M", "parameter": "mm/hr", "normalRange": "0 - 5" },
    { "name": "Blood Bank Test N", "parameter": "mmol/L", "normalRange": "90 - 120" },
    { "name": "Blood Bank Test O", "parameter": "ng/mL", "normalRange": "10 - 40" },
    { "name": "Blood Bank Test P", "parameter": "mg/dL", "normalRange": "150 - 450" },
    { "name": "Blood Bank Test Q", "parameter": "IU/L", "normalRange": "10 - 40" },
    { "name": "Blood Bank Test R", "parameter": "mm/hr", "normalRange": "0 - 5" },
    { "name": "Blood Bank Test S", "parameter": "ng/mL", "normalRange": "0 - 20" },
    { "name": "Blood Bank Test T", "parameter": "g/dL", "normalRange": "150 - 450" }
  ],
  "Cytology": [
    { "name": "Cytology Test A", "parameter": "cells/uL", "normalRange": "90 - 120" },
    { "name": "Cytology Test B", "parameter": "mg/dL", "normalRange": "70 - 100" },
    { "name": "Cytology Test C", "parameter": "mmol/L", "normalRange": "0 - 20" },
    { "name": "Cytology Test D", "parameter": "ng/mL", "normalRange": "90 - 120" },
    { "name": "Cytology Test E", "parameter": "IU/L", "normalRange": "20 - 200" },
    { "name": "Cytology Test F", "parameter": "ng/mL", "normalRange": "0.5 - 2.0" },
    { "name": "Cytology Test G", "parameter": "mm/hr", "normalRange": "10 - 40" },
    { "name": "Cytology Test H", "parameter": "mg/dL", "normalRange": "3.5 - 5.5" },
    { "name": "Cytology Test I", "parameter": "g/dL", "normalRange": "20 - 200" },
    { "name": "Cytology Test J", "parameter": "mm/hr", "normalRange": "150 - 450" },
    { "name": "Cytology Test K", "parameter": "mmol/L", "normalRange": "70 - 100" },
    { "name": "Cytology Test L", "parameter": "mm/hr", "normalRange": "12 - 16" },
    { "name": "Cytology Test M", "parameter": "ng/mL", "normalRange": "0 - 5" },
    { "name": "Cytology Test N", "parameter": "cells/uL", "normalRange": "70 - 100" },
    { "name": "Cytology Test O", "parameter": "g/dL", "normalRange": "70 - 100" },
    { "name": "Cytology Test P", "parameter": "mg/dL", "normalRange": "150 - 450" },
    { "name": "Cytology Test Q", "parameter": "g/dL", "normalRange": "12 - 16" },
    { "name": "Cytology Test R", "parameter": "cells/uL", "normalRange": "70 - 100" },
    { "name": "Cytology Test S", "parameter": "ng/mL", "normalRange": "10 - 40" },
    { "name": "Cytology Test T", "parameter": "ng/mL", "normalRange": "90 - 120" }
  ],
  "Dermatology": [
    { "name": "Dermatology Test A", "parameter": "mm/hr", "normalRange": "3.5 - 5.5" },
    { "name": "Dermatology Test B", "parameter": "mg/dL", "normalRange": "90 - 120" },
    { "name": "Dermatology Test C", "parameter": "ng/mL", "normalRange": "20 - 200" },
    { "name": "Dermatology Test D", "parameter": "ng/mL", "normalRange": "90 - 120" },
    { "name": "Dermatology Test E", "parameter": "mg/dL", "normalRange": "12 - 16" },
    { "name": "Dermatology Test F", "parameter": "g/dL", "normalRange": "12 - 16" },
    { "name": "Dermatology Test G", "parameter": "mm/hr", "normalRange": "0.5 - 2.0" },
    { "name": "Dermatology Test H", "parameter": "cells/uL", "normalRange": "20 - 200" },
    { "name": "Dermatology Test I", "parameter": "IU/L", "normalRange": "3.5 - 5.5" },
    { "name": "Dermatology Test J", "parameter": "g/dL", "normalRange": "0.5 - 2.0" },
    { "name": "Dermatology Test K", "parameter": "mm/hr", "normalRange": "0 - 5" },
    { "name": "Dermatology Test L", "parameter": "ng/mL", "normalRange": "0 - 20" },
    { "name": "Dermatology Test M", "parameter": "IU/L", "normalRange": "90 - 120" },
    { "name": "Dermatology Test N", "parameter": "g/dL", "normalRange": "0 - 5" },
    { "name": "Dermatology Test O", "parameter": "cells/uL", "normalRange": "3.5 - 5.5" },
    { "name": "Dermatology Test P", "parameter": "g/dL", "normalRange": "12 - 16" },
    { "name": "Dermatology Test Q", "parameter": "mmol/L", "normalRange": "150 - 450" },
    { "name": "Dermatology Test R", "parameter": "mg/dL", "normalRange": "70 - 100" },
    { "name": "Dermatology Test S", "parameter": "mm/hr", "normalRange": "10 - 40" },
    { "name": "Dermatology Test T", "parameter": "IU/L", "normalRange": "10 - 40" }
  ],
  "Cardiology": [
    { "name": "Cardiology Test A", "parameter": "cells/uL", "normalRange": "0 - 20" },
    { "name": "Cardiology Test B", "parameter": "IU/L", "normalRange": "20 - 200" },
    { "name": "Cardiology Test C", "parameter": "ng/mL", "normalRange": "0 - 5" },
    { "name": "Cardiology Test D", "parameter": "mg/dL", "normalRange": "0 - 5" },
    { "name": "Cardiology Test E", "parameter": "mg/dL", "normalRange": "3.5 - 5.5" },
    { "name": "Cardiology Test F", "parameter": "ng/mL", "normalRange": "20 - 200" },
    { "name": "Cardiology Test G", "parameter": "g/dL", "normalRange": "10 - 40" },
    { "name": "Cardiology Test H", "parameter": "g/dL", "normalRange": "0 - 20" },
    { "name": "Cardiology Test I", "parameter": "mg/dL", "normalRange": "70 - 100" },
    { "name": "Cardiology Test J", "parameter": "mg/dL", "normalRange": "150 - 450" },
    { "name": "Cardiology Test K", "parameter": "g/dL", "normalRange": "12 - 16" },
    { "name": "Cardiology Test L", "parameter": "cells/uL", "normalRange": "70 - 100" },
    { "name": "Cardiology Test M", "parameter": "mm/hr", "normalRange": "10 - 40" },
    { "name": "Cardiology Test N", "parameter": "mmol/L", "normalRange": "10 - 40" },
    { "name": "Cardiology Test O", "parameter": "cells/uL", "normalRange": "0 - 20" },
    { "name": "Cardiology Test P", "parameter": "g/dL", "normalRange": "150 - 450" },
    { "name": "Cardiology Test Q", "parameter": "mg/dL", "normalRange": "12 - 16" },
    { "name": "Cardiology Test R", "parameter": "ng/mL", "normalRange": "12 - 16" },
    { "name": "Cardiology Test S", "parameter": "cells/uL", "normalRange": "150 - 450" },
    { "name": "Cardiology Test T", "parameter": "mg/dL", "normalRange": "90 - 120" }
  ],
  "Neurology": [
    { "name": "Neurology Test A", "parameter": "IU/L", "normalRange": "0 - 5" },
    { "name": "Neurology Test B", "parameter": "mg/dL", "normalRange": "0 - 20" },
    { "name": "Neurology Test C", "parameter": "mm/hr", "normalRange": "3.5 - 5.5" },
    { "name": "Neurology Test D", "parameter": "mg/dL", "normalRange": "150 - 450" },
    { "name": "Neurology Test E", "parameter": "IU/L", "normalRange": "0.5 - 2.0" },
    { "name": "Neurology Test F", "parameter": "g/dL", "normalRange": "0.5 - 2.0" },
    { "name": "Neurology Test G", "parameter": "cells/uL", "normalRange": "10 - 40" },
    { "name": "Neurology Test H", "parameter": "mg/dL", "normalRange": "20 - 200" },
    { "name": "Neurology Test I", "parameter": "mg/dL", "normalRange": "0 - 20" },
    { "name": "Neurology Test J", "parameter": "mm/hr", "normalRange": "0 - 5" },
    { "name": "Neurology Test K", "parameter": "ng/mL", "normalRange": "3.5 - 5.5" },
    { "name": "Neurology Test L", "parameter": "ng/mL", "normalRange": "0 - 20" },
    { "name": "Neurology Test M", "parameter": "mmol/L", "normalRange": "0.5 - 2.0" },
    { "name": "Neurology Test N", "parameter": "mmol/L", "normalRange": "12 - 16" },
    { "name": "Neurology Test O", "parameter": "g/dL", "normalRange": "0 - 5" },
    { "name": "Neurology Test P", "parameter": "IU/L", "normalRange": "70 - 100" },
    { "name": "Neurology Test Q", "parameter": "IU/L", "normalRange": "20 - 200" },
    { "name": "Neurology Test R", "parameter": "ng/mL", "normalRange": "0 - 20" },
    { "name": "Neurology Test S", "parameter": "mmol/L", "normalRange": "12 - 16" },
    { "name": "Neurology Test T", "parameter": "mg/dL", "normalRange": "12 - 16" }
  ],
  "Gastroenterology": [
    { "name": "Gastroenterology Test A", "parameter": "IU/L", "normalRange": "10 - 40" },
    { "name": "Gastroenterology Test B", "parameter": "cells/uL", "normalRange": "150 - 450" },
    { "name": "Gastroenterology Test C", "parameter": "cells/uL", "normalRange": "0 - 20" },
    { "name": "Gastroenterology Test D", "parameter": "mmol/L", "normalRange": "0 - 20" },
    { "name": "Gastroenterology Test E", "parameter": "g/dL", "normalRange": "20 - 200" },
    { "name": "Gastroenterology Test F", "parameter": "mmol/L", "normalRange": "150 - 450" },
    { "name": "Gastroenterology Test G", "parameter": "mm/hr", "normalRange": "10 - 40" },
    { "name": "Gastroenterology Test H", "parameter": "ng/mL", "normalRange": "70 - 100" },
    { "name": "Gastroenterology Test I", "parameter": "cells/uL", "normalRange": "150 - 450" },
    { "name": "Gastroenterology Test J", "parameter": "g/dL", "normalRange": "10 - 40" },
    { "name": "Gastroenterology Test K", "parameter": "ng/mL", "normalRange": "20 - 200" },
    { "name": "Gastroenterology Test L", "parameter": "mm/hr", "normalRange": "150 - 450" },
    { "name": "Gastroenterology Test M", "parameter": "mmol/L", "normalRange": "12 - 16" },
    { "name": "Gastroenterology Test N", "parameter": "g/dL", "normalRange": "150 - 450" },
    { "name": "Gastroenterology Test O", "parameter": "mmol/L", "normalRange": "0 - 5" },
    { "name": "Gastroenterology Test P", "parameter": "mm/hr", "normalRange": "10 - 40" },
    { "name": "Gastroenterology Test Q", "parameter": "cells/uL", "normalRange": "12 - 16" },
    { "name": "Gastroenterology Test R", "parameter": "mmol/L", "normalRange": "0 - 5" },
    { "name": "Gastroenterology Test S", "parameter": "ng/mL", "normalRange": "20 - 200" },
    { "name": "Gastroenterology Test T", "parameter": "mg/dL", "normalRange": "20 - 200" }
  ],
  "Nephrology": [
    { "name": "Nephrology Test A", "parameter": "IU/L", "normalRange": "12 - 16" },
    { "name": "Nephrology Test B", "parameter": "g/dL", "normalRange": "0.5 - 2.0" },
    { "name": "Nephrology Test C", "parameter": "cells/uL", "normalRange": "70 - 100" },
    { "name": "Nephrology Test D", "parameter": "ng/mL", "normalRange": "0.5 - 2.0" },
    { "name": "Nephrology Test E", "parameter": "cells/uL", "normalRange": "150 - 450" },
    { "name": "Nephrology Test F", "parameter": "ng/mL", "normalRange": "10 - 40" },
    { "name": "Nephrology Test G", "parameter": "ng/mL", "normalRange": "20 - 200" },
    { "name": "Nephrology Test H", "parameter": "mm/hr", "normalRange": "10 - 40" },
    { "name": "Nephrology Test I", "parameter": "mmol/L", "normalRange": "20 - 200" },
    { "name": "Nephrology Test J", "parameter": "mm/hr", "normalRange": "10 - 40" },
    { "name": "Nephrology Test K", "parameter": "cells/uL", "normalRange": "90 - 120" },
    { "name": "Nephrology Test L", "parameter": "mm/hr", "normalRange": "70 - 100" },
    { "name": "Nephrology Test M", "parameter": "cells/uL", "normalRange": "12 - 16" },
    { "name": "Nephrology Test N", "parameter": "mmol/L", "normalRange": "20 - 200" },
    { "name": "Nephrology Test O", "parameter": "g/dL", "normalRange": "12 - 16" },
    { "name": "Nephrology Test P", "parameter": "g/dL", "normalRange": "70 - 100" },
    { "name": "Nephrology Test Q", "parameter": "cells/uL", "normalRange": "90 - 120" },
    { "name": "Nephrology Test R", "parameter": "ng/mL", "normalRange": "20 - 200" },
    { "name": "Nephrology Test S", "parameter": "IU/L", "normalRange": "0.5 - 2.0" },
    { "name": "Nephrology Test T", "parameter": "g/dL", "normalRange": "0.5 - 2.0" }
  ],
  "Pulmonology": [
    { "name": "Pulmonology Test A", "parameter": "mg/dL", "normalRange": "0.5 - 2.0" },
    { "name": "Pulmonology Test B", "parameter": "IU/L", "normalRange": "3.5 - 5.5" },
    { "name": "Pulmonology Test C", "parameter": "mm/hr", "normalRange": "10 - 40" },
    { "name": "Pulmonology Test D", "parameter": "ng/mL", "normalRange": "70 - 100" },
    { "name": "Pulmonology Test E", "parameter": "ng/mL", "normalRange": "90 - 120" },
    { "name": "Pulmonology Test F", "parameter": "mg/dL", "normalRange": "0 - 20" },
    { "name": "Pulmonology Test G", "parameter": "ng/mL", "normalRange": "70 - 100" },
    { "name": "Pulmonology Test H", "parameter": "mmol/L", "normalRange": "12 - 16" },
    { "name": "Pulmonology Test I", "parameter": "cells/uL", "normalRange": "0 - 5" },
    { "name": "Pulmonology Test J", "parameter": "mg/dL", "normalRange": "70 - 100" },
    { "name": "Pulmonology Test K", "parameter": "mg/dL", "normalRange": "90 - 120" },
    { "name": "Pulmonology Test L", "parameter": "mg/dL", "normalRange": "0 - 5" },
    { "name": "Pulmonology Test M", "parameter": "IU/L", "normalRange": "12 - 16" },
    { "name": "Pulmonology Test N", "parameter": "ng/mL", "normalRange": "10 - 40" },
    { "name": "Pulmonology Test O", "parameter": "mm/hr", "normalRange": "0.5 - 2.0" },
    { "name": "Pulmonology Test P", "parameter": "mmol/L", "normalRange": "12 - 16" },
    { "name": "Pulmonology Test Q", "parameter": "cells/uL", "normalRange": "10 - 40" },
    { "name": "Pulmonology Test R", "parameter": "mg/dL", "normalRange": "150 - 450" },
    { "name": "Pulmonology Test S", "parameter": "mmol/L", "normalRange": "70 - 100" },
    { "name": "Pulmonology Test T", "parameter": "g/dL", "normalRange": "10 - 40" }
  ],
  "Rheumatology": [
    { "name": "Rheumatology Test A", "parameter": "mg/dL", "normalRange": "12 - 16" },
    { "name": "Rheumatology Test B", "parameter": "mmol/L", "normalRange": "3.5 - 5.5" },
    { "name": "Rheumatology Test C", "parameter": "mg/dL", "normalRange": "20 - 200" },
    { "name": "Rheumatology Test D", "parameter": "cells/uL", "normalRange": "150 - 450" },
    { "name": "Rheumatology Test E", "parameter": "mg/dL", "normalRange": "3.5 - 5.5" },
    { "name": "Rheumatology Test F", "parameter": "ng/mL", "normalRange": "0 - 5" },
    { "name": "Rheumatology Test G", "parameter": "g/dL", "normalRange": "0.5 - 2.0" },
    { "name": "Rheumatology Test H", "parameter": "mm/hr", "normalRange": "0 - 5" },
    { "name": "Rheumatology Test I", "parameter": "ng/mL", "normalRange": "0.5 - 2.0" },
    { "name": "Rheumatology Test J", "parameter": "mg/dL", "normalRange": "150 - 450" },
    { "name": "Rheumatology Test K", "parameter": "IU/L", "normalRange": "150 - 450" },
    { "name": "Rheumatology Test L", "parameter": "mg/dL", "normalRange": "20 - 200" },
    { "name": "Rheumatology Test M", "parameter": "ng/mL", "normalRange": "20 - 200" },
    { "name": "Rheumatology Test N", "parameter": "mmol/L", "normalRange": "150 - 450" },
    { "name": "Rheumatology Test O", "parameter": "g/dL", "normalRange": "10 - 40" },
    { "name": "Rheumatology Test P", "parameter": "ng/mL", "normalRange": "70 - 100" },
    { "name": "Rheumatology Test Q", "parameter": "mg/dL", "normalRange": "10 - 40" },
    { "name": "Rheumatology Test R", "parameter": "g/dL", "normalRange": "0 - 5" },
    { "name": "Rheumatology Test S", "parameter": "mm/hr", "normalRange": "150 - 450" },
    { "name": "Rheumatology Test T", "parameter": "g/dL", "normalRange": "3.5 - 5.5" }
  ],
  "Infectious Diseases": [
    { "name": "Infectious Diseases Test A", "parameter": "g/dL", "normalRange": "10 - 40" },
    { "name": "Infectious Diseases Test B", "parameter": "ng/mL", "normalRange": "3.5 - 5.5" },
    { "name": "Infectious Diseases Test C", "parameter": "mmol/L", "normalRange": "3.5 - 5.5" },
    { "name": "Infectious Diseases Test D", "parameter": "mg/dL", "normalRange": "0.5 - 2.0" },
    { "name": "Infectious Diseases Test E", "parameter": "ng/mL", "normalRange": "3.5 - 5.5" },
    { "name": "Infectious Diseases Test F", "parameter": "mm/hr", "normalRange": "10 - 40" },
    { "name": "Infectious Diseases Test G", "parameter": "mm/hr", "normalRange": "70 - 100" },
    { "name": "Infectious Diseases Test H", "parameter": "ng/mL", "normalRange": "150 - 450" },
    { "name": "Infectious Diseases Test I", "parameter": "g/dL", "normalRange": "3.5 - 5.5" },
    { "name": "Infectious Diseases Test J", "parameter": "mg/dL", "normalRange": "3.5 - 5.5" },
    { "name": "Infectious Diseases Test K", "parameter": "cells/uL", "normalRange": "0 - 5" },
    { "name": "Infectious Diseases Test L", "parameter": "g/dL", "normalRange": "20 - 200" },
    { "name": "Infectious Diseases Test M", "parameter": "cells/uL", "normalRange": "3.5 - 5.5" },
    { "name": "Infectious Diseases Test N", "parameter": "IU/L", "normalRange": "12 - 16" },
    { "name": "Infectious Diseases Test O", "parameter": "g/dL", "normalRange": "150 - 450" },
    { "name": "Infectious Diseases Test P", "parameter": "mmol/L", "normalRange": "70 - 100" },
    { "name": "Infectious Diseases Test Q", "parameter": "mm/hr", "normalRange": "0.5 - 2.0" },
    { "name": "Infectious Diseases Test R", "parameter": "cells/uL", "normalRange": "10 - 40" },
    { "name": "Infectious Diseases Test S", "parameter": "mmol/L", "normalRange": "0 - 20" },
    { "name": "Infectious Diseases Test T", "parameter": "cells/uL", "normalRange": "70 - 100" }
  ],
  "Sports Medicine": [
    { "name": "Sports Medicine Test A", "parameter": "mg/dL", "normalRange": "150 - 450" },
    { "name": "Sports Medicine Test B", "parameter": "mm/hr", "normalRange": "0.5 - 2.0" },
    { "name": "Sports Medicine Test C", "parameter": "ng/mL", "normalRange": "90 - 120" },
    { "name": "Sports Medicine Test D", "parameter": "g/dL", "normalRange": "0.5 - 2.0" },
    { "name": "Sports Medicine Test E", "parameter": "cells/uL", "normalRange": "20 - 200" },
    { "name": "Sports Medicine Test F", "parameter": "cells/uL", "normalRange": "150 - 450" },
    { "name": "Sports Medicine Test G", "parameter": "mm/hr", "normalRange": "3.5 - 5.5" },
    { "name": "Sports Medicine Test H", "parameter": "cells/uL", "normalRange": "10 - 40" },
    { "name": "Sports Medicine Test I", "parameter": "mmol/L", "normalRange": "150 - 450" },
    { "name": "Sports Medicine Test J", "parameter": "mm/hr", "normalRange": "0 - 20" },
    { "name": "Sports Medicine Test K", "parameter": "mm/hr", "normalRange": "10 - 40" },
    { "name": "Sports Medicine Test L", "parameter": "mm/hr", "normalRange": "10 - 40" },
    { "name": "Sports Medicine Test M", "parameter": "cells/uL", "normalRange": "90 - 120" },
    { "name": "Sports Medicine Test N", "parameter": "mg/dL", "normalRange": "20 - 200" },
    { "name": "Sports Medicine Test O", "parameter": "mmol/L", "normalRange": "90 - 120" },
    { "name": "Sports Medicine Test P", "parameter": "ng/mL", "normalRange": "0 - 5" },
    { "name": "Sports Medicine Test Q", "parameter": "cells/uL", "normalRange": "10 - 40" },
    { "name": "Sports Medicine Test R", "parameter": "mg/dL", "normalRange": "150 - 450" },
    { "name": "Sports Medicine Test S", "parameter": "cells/uL", "normalRange": "0.5 - 2.0" },
    { "name": "Sports Medicine Test T", "parameter": "cells/uL", "normalRange": "150 - 450" }
  ],
  "Occupational Health": [
    { "name": "Occupational Health Test A", "parameter": "mmol/L", "normalRange": "12 - 16" },
    { "name": "Occupational Health Test B", "parameter": "g/dL", "normalRange": "0 - 20" },
    { "name": "Occupational Health Test C", "parameter": "mg/dL", "normalRange": "70 - 100" },
    { "name": "Occupational Health Test D", "parameter": "cells/uL", "normalRange": "20 - 200" },
    { "name": "Occupational Health Test E", "parameter": "ng/mL", "normalRange": "0 - 5" },
    { "name": "Occupational Health Test F", "parameter": "cells/uL", "normalRange": "0 - 20" },
    { "name": "Occupational Health Test G", "parameter": "ng/mL", "normalRange": "20 - 200" },
    { "name": "Occupational Health Test H", "parameter": "cells/uL", "normalRange": "90 - 120" },
    { "name": "Occupational Health Test I", "parameter": "mmol/L", "normalRange": "3.5 - 5.5" },
    { "name": "Occupational Health Test J", "parameter": "mg/dL", "normalRange": "20 - 200" },
    { "name": "Occupational Health Test K", "parameter": "IU/L", "normalRange": "20 - 200" },
    { "name": "Occupational Health Test L", "parameter": "ng/mL", "normalRange": "90 - 120" },
    { "name": "Occupational Health Test M", "parameter": "mmol/L", "normalRange": "0 - 20" },
    { "name": "Occupational Health Test N", "parameter": "mmol/L", "normalRange": "10 - 40" },
    { "name": "Occupational Health Test O", "parameter": "mm/hr", "normalRange": "20 - 200" },
    { "name": "Occupational Health Test P", "parameter": "mmol/L", "normalRange": "0.5 - 2.0" },
    { "name": "Occupational Health Test Q", "parameter": "g/dL", "normalRange": "10 - 40" },
    { "name": "Occupational Health Test R", "parameter": "cells/uL", "normalRange": "90 - 120" },
    { "name": "Occupational Health Test S", "parameter": "ng/mL", "normalRange": "150 - 450" },
    { "name": "Occupational Health Test T", "parameter": "cells/uL", "normalRange": "150 - 450" }
  ],
  "General Screening": [
    { "name": "General Screening Test A", "parameter": "cells/uL", "normalRange": "0 - 5" },
    { "name": "General Screening Test B", "parameter": "mmol/L", "normalRange": "0 - 5" },
    { "name": "General Screening Test C", "parameter": "cells/uL", "normalRange": "70 - 100" },
    { "name": "General Screening Test D", "parameter": "cells/uL", "normalRange": "10 - 40" },
    { "name": "General Screening Test E", "parameter": "ng/mL", "normalRange": "90 - 120" },
    { "name": "General Screening Test F", "parameter": "mg/dL", "normalRange": "3.5 - 5.5" },
    { "name": "General Screening Test G", "parameter": "ng/mL", "normalRange": "150 - 450" },
    { "name": "General Screening Test H", "parameter": "g/dL", "normalRange": "12 - 16" },
    { "name": "General Screening Test I", "parameter": "cells/uL", "normalRange": "0 - 20" },
    { "name": "General Screening Test J", "parameter": "mg/dL", "normalRange": "20 - 200" },
    { "name": "General Screening Test K", "parameter": "ng/mL", "normalRange": "0 - 5" },
    { "name": "General Screening Test L", "parameter": "IU/L", "normalRange": "3.5 - 5.5" },
    { "name": "General Screening Test M", "parameter": "g/dL", "normalRange": "3.5 - 5.5" },
    { "name": "General Screening Test N", "parameter": "cells/uL", "normalRange": "12 - 16" },
    { "name": "General Screening Test O", "parameter": "IU/L", "normalRange": "90 - 120" },
    { "name": "General Screening Test P", "parameter": "IU/L", "normalRange": "0.5 - 2.0" },
    { "name": "General Screening Test Q", "parameter": "cells/uL", "normalRange": "90 - 120" },
    { "name": "General Screening Test R", "parameter": "ng/mL", "normalRange": "20 - 200" },
    { "name": "General Screening Test S", "parameter": "mmol/L", "normalRange": "150 - 450" },
    { "name": "General Screening Test T", "parameter": "cells/uL", "normalRange": "0 - 20" }
  ]
};